### ISSUE TITLE
Document how to run nebula on Windows

### ISSUE THREAD

**Issue by jasikpark** [DefinedNet/nebula-docs#103]

**Comment by csawyerYumaed** [comment]
This is my quick and dirty guide

create a folder C:\nebula

extract the zip file there, including the dist\ folder

copy over your config.yml file and keys
make sure you have tun device setup in the yaml:
 ```
 tun:
  disabled: false
  dev: tun0
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1422
 ```
if you do not, you will get an error about tun parameters wrong or something.

start powershell as administrator
cd \nebula
./nebula.exe -service install

check the service from the services app(search services from the start/win menu) as administrator: then scroll down to nebula that will let you start/stop the service if needed.

It will also show you the command line it's running, so you can run it yourself and debug any issues that crop up.
